/* Support for bitmap fonts generated by https://github.com/achilikin/bdfe
  
   Copyright (c) 2015 Andrey Chilikin (https://github.com/achilikin)

   Permission is hereby granted, free of charge, to any person obtaining a copy
   of this software and associated documentation files (the "Software"), to deal
   in the Software without restriction, including without limitation the rights
   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
   copies of the Software, and to permit persons to whom the Software is
   furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in
   all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
   THE SOFTWARE.
   https://opensource.org/licenses/MIT
*/
#include <stdio.h>
#ifdef __AVR_ARCH__
	#include <avr/pgmspace.h>
#else
	#define PROGMEM
#endif

#include "bmfont.h"

#if USE_BMFONT_6x8
static const uint8_t font68[] PROGMEM = {
#include "font6x8.h"
};
#endif

static const uint8_t font88[] PROGMEM = {
#include "font88.h"
};

static const uint8_t font816[] PROGMEM = {
#include "font816.h"
};

static bmfont_t _ofont[BMFONT_MAX+1] = {
#if USE_BMFONT_6x8
	{  6,  8, 32, 127-32, font68 },	
#endif
	{  8,  8, 32, 127-32, font88 },
	{  8, 16, 32, 127-32, font816 },
	{  0,  0, 0,       0, NULL }
};

static uint8_t _cfont;

uint8_t bmfont_select(uint8_t font)
{
	uint8_t fret = _cfont;
	if (font <= BMFONT_MAX)
		_cfont = font;
	return fret;
}

bmfont_t *bmfont_get(void)
{
	return &_ofont[_cfont];
}

void bmfont_set(bmfont_t *nfont, bmfont_t *ofont)
{
	if (ofont) {
		ofont->gw = _ofont[BMFONT_USER].gw;
		ofont->gh = _ofont[BMFONT_USER].gh;
		ofont->go = _ofont[BMFONT_USER].go;
		ofont->gn = _ofont[BMFONT_USER].gn;
		ofont->font = _ofont[BMFONT_USER].font;
	}
	_ofont[BMFONT_USER].gw = nfont->gw;
	_ofont[BMFONT_USER].gh = nfont->gh; 
	_ofont[BMFONT_USER].go = nfont->go;
	_ofont[BMFONT_USER].gn = nfont->gn;
	_ofont[BMFONT_USER].font = nfont->font;
}
